version: '3.3'

networks:
    backend:
        driver: bridge

services:
    php:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        depends_on:
            - mysql
        volumes:
            - .:/var/www:cached
        networks:
            - backend
    nginx:
        build:
            context: .
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - '80:80'
        volumes:
            - .:/var/www:cached
        depends_on:
            - php
        networks:
            - backend
    mysql:
        build:
            context: .
            dockerfile: .docker/mysql/Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: local
            MYSQL_USER: local
            MYSQL_PASSWORD: local
            TZ: 'Asia/Tokyo'
        ports:
            - '3304:3306'
        networks:
            - backend

volumes:
    node_modules_volume:
